#!/home/ruimc/Tool-X/venv/bin/python3

import os
import sys
import shutil

def main():
    if len(sys.argv) < 2:
        print("[ERROR] -> Missing file argument", file=sys.stderr)
        print(f"Usage: {sys.argv[0]} <file1> <file2> ...", file=sys.stderr)
        sys.exit(1)

    for path in sys.argv[1:]:
        try:
            if os.path.isfile(path):
                os.remove(path)

            elif os.path.isdir(path):
                shutil.rmtree(path)
                
        except FileNotFoundError:
            print(f"Error: file '{path}' not found.", file=sys.stderr)
        except PermissionError:
            print(f"Error: permission denied to access '{path}'.", file=sys.stderr)
        except IsADirectoryError:
            print(f"Error: '{path}' is a directory, not a file.", file=sys.stderr)
        except Exception as e:
            print(f"Error: could not delete '{path}': {e}", file=sys.stderr)

if __name__ == "__main__":
    main()
